CREATE TABLE IF NOT EXISTS Customers (
  Customer_ID CHAR(20) NOT NULL,
  Customer_Name VARCHAR(45) NOT NULL,
  Customer_PW VARCHAR(50) NOT NULL,
  Taste_Sugar INT(10)UNSIGNED NULL,
  Taste_Sour INT(10)UNSIGNED NULL,
  Taste_Flavor INT(10)UNSIGNED NULL,
  PRIMARY KEY (Customer_ID));