CREATE TABLE IF NOT EXISTS Beer_Score (
  Beer_ID INT(10)UNSIGNED NULL,
  Taste_Sugar INT(10)UNSIGNED NULL,
  Taste_Sour INT(10)UNSIGNED NULL,
  Taste_Flavor INT(10)UNSIGNED NULL,
  PRIMARY KEY (Beer_ID));